import React, { useState } from 'react';
import { Drill, Player } from '../../types';
import JSZip from 'jszip';
import { 
  Github, 
  Download, 
  Upload, 
  Copy, 
  Check, 
  X, 
  FileCode, 
  FolderArchive,
  ExternalLink,
  MousePointerClick,
  Terminal,
  Globe,
  CheckCircle2,
  Sparkles,
  Layers
} from 'lucide-react';

interface GitHubExportModalProps {
  drills: Drill[];
  players: Player[];
  onClose: () => void;
  onImportSuccess: (drillCount: number, playerCount: number) => void;
}

export const GitHubExportModal: React.FC<GitHubExportModalProps> = ({
  drills,
  players,
  onClose,
  onImportSuccess,
}) => {
  const [activeTab, setActiveTab] = useState<'web_deploy' | 'browser_upload' | 'git_terminal' | 'json_backup'>('web_deploy');
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [repoName, setRepoName] = useState('fleiss-gk-studio');
  const [githubUsername, setGithubUsername] = useState('');

  const gitCommands = `# 1. リポジトリ用のフォルダに移動
cd ${repoName}

# 2. Gitを初期化してすべてのファイルを追加
git init
git add .
git commit -m "feat: FLEISS Goalkeeper Studio Webアプリ初期コミット"

# 3. メインブランチに切り替え
git branch -M main

# 4. あなたのGitHubリポジトリを登録（${githubUsername || 'YOUR_USERNAME'} をあなたのアカウント名に）
git remote add origin https://github.com/${githubUsername || 'YOUR_USERNAME'}/${repoName}.git

# 5. GitHubへプッシュ！
git push -u origin main`;

  const handleCopyCommands = () => {
    navigator.clipboard.writeText(gitCommands);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Generate and Download Full GitHub Ready ZIP with deploy config
  const handleDownloadZip = async () => {
    setIsGenerating(true);
    try {
      const zip = new JSZip();

      // 1. README.md
      const readmeContent = `# FLEISS Goalkeeper Studio - Web Application
GK専門トレーニングメニュー無制限作成 & タクティカルボード & 選手管理システム

## 🚀 Web公開について (GitHub Pages / Vercel対応)
本リポジトリは、GitHub PagesまたはVercelで即座にWebサイトとして公開可能な設定が含まれています。

### 🌐 GitHub Pagesで公開する場合:
1. GitHubの該当リポジトリの **Settings** > **Pages** を開く
2. **Build and deployment** > **Source** で **「GitHub Actions」** を選択
3. 自動的に \`.github/workflows/deploy.yml\` が実行され、数分で \`https://<ユーザー名>.github.io/${repoName}/\` に公開されます！

### ⚡ Vercelで公開する場合（一番簡単・おすすめ）:
1. [Vercel.com](https://vercel.com) にログイン
2. **Add New Project** から本リポジトリを選択して **Deploy** を押すだけ！

---

## 登録データ概要
- 登録メニュー数: ${drills.length} 件
${drills.map((d, i) => `${i + 1}. **[${d.title}](./drills/${d.id}.md)** (${d.category} / ${d.durationMinutes}分)`).join('\n')}
- 登録GK選手数: ${players.length} 名
${players.map((p, i) => `${i + 1}. **${p.name}** (${p.category} / #${p.number})`).join('\n')}

---
Generated by FLEISS Goalkeeper Studio (fleiss.gk.school@gmail.com)
`;
      zip.file('README.md', readmeContent);

      // 2. .gitignore
      zip.file('.gitignore', `# Dependencies\nnode_modules/\n.pnp\n.pnp.js\n\n# Production\ndist/\n\n# Environment\n.env\n.env.local\n\n# OS\n.DS_Store\nThumbs.db\n`);

      // 3. .github/workflows/deploy.yml for auto GitHub Pages!
      const workflowsFolder = zip.folder('.github')?.folder('workflows');
      if (workflowsFolder) {
        const deployYml = `name: Deploy to GitHub Pages
on:
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - id: deployment
        uses: actions/deploy-pages@v4
`;
        workflowsFolder.file('deploy.yml', deployYml);
      }

      // 4. /data/drills.json & /data/players.json
      const dataFolder = zip.folder('data');
      if (dataFolder) {
        dataFolder.file('drills.json', JSON.stringify(drills, null, 2));
        dataFolder.file('players.json', JSON.stringify(players, null, 2));
      }

      // 5. /drills/*.md
      const drillsFolder = zip.folder('drills');
      if (drillsFolder) {
        drills.forEach(d => {
          const drillMd = `# ${d.title}
- カテゴリ: ${d.category}
- 対象: ${d.ageCategory}
- 所要時間: ${d.durationMinutes}分
- 強度: ${d.intensity}

## 目的
${d.objectives.map(o => `- ${o}`).join('\n')}

## 用具・グリッド
${d.setup}

## 手順
${d.procedure.map((p, i) => `${i + 1}. ${p}`).join('\n')}

## キーファクター
${d.coachingPoints.map(cp => `- ${cp}`).join('\n')}
`;
          drillsFolder.file(`${d.id}.md`, drillMd);
        });
      }

      const content = await zip.generateAsync({ type: 'blob' });
      const downloadUrl = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = downloadUrl;
      link.download = `${repoName}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(downloadUrl);
    } catch (e) {
      console.error(e);
      alert('ZIPの生成に失敗しました');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const text = event.target?.result as string;
        const parsed = JSON.parse(text);
        let drillCount = 0;
        let playerCount = 0;

        if (Array.isArray(parsed.drills)) {
          localStorage.setItem('fleiss_gk_drills_v1', JSON.stringify(parsed.drills));
          drillCount = parsed.drills.length;
        }
        if (Array.isArray(parsed.players)) {
          localStorage.setItem('fleiss_gk_players_v1', JSON.stringify(parsed.players));
          playerCount = parsed.players.length;
        }

        onImportSuccess(drillCount, playerCount);
        alert(`復元完了！ メニュー: ${drillCount}件、選手: ${playerCount}件を読み込みました。`);
        onClose();
      } catch (err) {
        alert('ファイルの読み込みに失敗しました。');
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xs">
      <div className="bg-white border border-neutral-200 rounded-3xl w-full max-w-4xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden font-sans text-neutral-800">
        {/* Header */}
        <div className="flex items-center justify-between px-8 py-5 border-b border-neutral-200 bg-[#081a2e] text-white">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-[#eab308] text-[#081a2e] font-extrabold shadow-md">
              <Globe className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-extrabold tracking-wide">
                GitHubに載せて、Webサイトとして触れるようにする方法
              </h2>
              <p className="text-xs text-neutral-300 mt-0.5">
                PC・タブレット・スマートフォンからどこでもアクセス可能に公開する手順
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-xl text-neutral-400 hover:text-white hover:bg-neutral-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="flex border-b border-neutral-200 bg-neutral-50 px-8 gap-6 text-xs overflow-x-auto custom-scrollbar">
          <button
            onClick={() => setActiveTab('web_deploy')}
            className={`py-3.5 font-bold transition-all border-b-2 -mb-px flex items-center gap-2 whitespace-nowrap ${
              activeTab === 'web_deploy'
                ? 'border-[#081a2e] text-[#081a2e]'
                : 'border-transparent text-neutral-500 hover:text-neutral-800'
            }`}
          >
            <Sparkles className="w-4 h-4 text-[#eab308]" />
            <span>【おすすめ】無料Web公開手順（GitHub Pages / Vercel）</span>
          </button>
          <button
            onClick={() => setActiveTab('browser_upload')}
            className={`py-3.5 font-bold transition-all border-b-2 -mb-px flex items-center gap-2 whitespace-nowrap ${
              activeTab === 'browser_upload'
                ? 'border-[#081a2e] text-[#081a2e]'
                : 'border-transparent text-neutral-500 hover:text-neutral-800'
            }`}
          >
            <MousePointerClick className="w-4 h-4" />
            <span>ブラウザでドラッグ＆ドロップ</span>
          </button>
          <button
            onClick={() => setActiveTab('git_terminal')}
            className={`py-3.5 font-bold transition-all border-b-2 -mb-px flex items-center gap-2 whitespace-nowrap ${
              activeTab === 'git_terminal'
                ? 'border-[#081a2e] text-[#081a2e]'
                : 'border-transparent text-neutral-500 hover:text-neutral-800'
            }`}
          >
            <Terminal className="w-4 h-4" />
            <span>Gitコマンドでプッシュ</span>
          </button>
          <button
            onClick={() => setActiveTab('json_backup')}
            className={`py-3.5 font-bold transition-all border-b-2 -mb-px flex items-center gap-2 whitespace-nowrap ${
              activeTab === 'json_backup'
                ? 'border-[#081a2e] text-[#081a2e]'
                : 'border-transparent text-neutral-500 hover:text-neutral-800'
            }`}
          >
            <Upload className="w-4 h-4" />
            <span>バックアップ復元</span>
          </button>
        </div>

        {/* Tab Body */}
        <div className="flex-1 overflow-y-auto p-8 space-y-6 text-xs custom-scrollbar">
          {/* TAB 1: Web Deploy (GitHub Pages & Vercel) */}
          {activeTab === 'web_deploy' && (
            <div className="space-y-6">
              {/* Highlight Card */}
              <div className="bg-emerald-50 border border-emerald-200 p-5 rounded-2xl flex items-start gap-4">
                <div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center shrink-0">
                  <CheckCircle2 className="w-5 h-5" />
                </div>
                <div className="space-y-1">
                  <h3 className="text-sm font-bold text-emerald-900">
                    はい、100%可能です！完全無料でWebサイトとして公開できます
                  </h3>
                  <p className="text-emerald-700 leading-relaxed text-xs">
                    GitHubにこのアプリのコードを載せると、**GitHub Pages** または **Vercel** を使って、
                    専用のWebアドレス（URL）が自動発行され、PCやiPad、スマートフォンからいつでも触れるようになります。
                  </p>
                </div>
              </div>

              {/* 2 Ways to Publish */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                {/* Method A: Vercel (Easiest) */}
                <div className="bg-white border-2 border-[#081a2e] p-6 rounded-2xl shadow-sm flex flex-col justify-between space-y-4">
                  <div className="space-y-2.5">
                    <div className="flex items-center justify-between">
                      <span className="px-2.5 py-1 rounded-full bg-[#fef3c7] text-[#92400e] text-[10px] font-extrabold uppercase">
                        一番おすすめ・設定1分
                      </span>
                      <span className="text-[11px] font-bold text-neutral-400">方法 A</span>
                    </div>
                    <h4 className="text-base font-extrabold text-[#081a2e]">
                      Vercel で公開する（無料・最も簡単）
                    </h4>
                    <p className="text-neutral-600 text-xs leading-relaxed">
                      GitHubリポジトリを選ぶだけで、設定不要で30秒で独自URLが発行されます。更新時も自動ビルドされます。
                    </p>
                    <ol className="space-y-1.5 text-neutral-700 text-xs pt-1">
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-[#081a2e]">1.</span>
                        <span>[vercel.com](https://vercel.com) でGitHubアカウントで無料ログイン</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-[#081a2e]">2.</span>
                        <span>「Add New Project」から作成したリポジトリを選択</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-[#081a2e]">3.</span>
                        <span>「Deploy」ボタンを押すだけで即座に公開URLが完成！</span>
                      </li>
                    </ol>
                  </div>
                  <a
                    href="https://vercel.com/new"
                    target="_blank"
                    rel="noreferrer"
                    className="w-full flex items-center justify-center gap-2 py-2.5 bg-[#081a2e] hover:bg-[#132c4a] text-white font-bold rounded-xl shadow-xs transition-colors"
                  >
                    <span>Vercelで新規デプロイを開く</span>
                    <ExternalLink className="w-3.5 h-3.5" />
                  </a>
                </div>

                {/* Method B: GitHub Pages */}
                <div className="bg-white border border-neutral-300 p-6 rounded-2xl shadow-sm flex flex-col justify-between space-y-4">
                  <div className="space-y-2.5">
                    <div className="flex items-center justify-between">
                      <span className="px-2.5 py-1 rounded-full bg-neutral-100 text-neutral-700 text-[10px] font-extrabold uppercase">
                        GitHub公式機能
                      </span>
                      <span className="text-[11px] font-bold text-neutral-400">方法 B</span>
                    </div>
                    <h4 className="text-base font-extrabold text-[#081a2e]">
                      GitHub Pages で公開する（完全無料）
                    </h4>
                    <p className="text-neutral-600 text-xs leading-relaxed">
                      アプリ内にすでに自動公開設定（<code>.github/workflows/deploy.yml</code>）が組み込まれているため、GitHubの設定を1箇所変更するだけで動きます。
                    </p>
                    <ol className="space-y-1.5 text-neutral-700 text-xs pt-1">
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-[#081a2e]">1.</span>
                        <span>GitHubの対象リポジトリ画面で <strong>Settings</strong> を開く</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-[#081a2e]">2.</span>
                        <span>左メニューの <strong>Pages</strong> をクリック</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-[#081a2e]">3.</span>
                        <span>Source で <strong>「GitHub Actions」</strong> を選ぶだけ！</span>
                      </li>
                    </ol>
                  </div>
                  <div className="text-[11px] text-neutral-500 bg-neutral-50 p-2.5 rounded-xl border border-neutral-200">
                    公開URL: <code className="font-mono text-[#081a2e]">https://&lt;ユーザー名&gt;.github.io/{repoName}/</code>
                  </div>
                </div>
              </div>

              {/* Download Package Action */}
              <div className="bg-[#f8fafc] border border-neutral-200 p-5 rounded-2xl flex flex-col sm:flex-row items-center justify-between gap-4">
                <div>
                  <h4 className="font-bold text-[#081a2e] text-sm">
                    まずはGitHubアップロード用パッケージをダウンロード
                  </h4>
                  <p className="text-neutral-500 text-xs">
                    自動デプロイ設定（deploy.yml）と全メニュー・作図データが含まれたZIPです。
                  </p>
                </div>
                <button
                  onClick={handleDownloadZip}
                  disabled={isGenerating}
                  className="flex items-center gap-2 px-5 py-2.5 bg-[#f59e0b] hover:bg-[#d97706] text-[#081a2e] font-extrabold rounded-xl shadow-xs transition-colors shrink-0"
                >
                  <Download className="w-4 h-4" />
                  <span>{isGenerating ? '生成中...' : 'GitHub準備完了ZIPをダウンロード'}</span>
                </button>
              </div>
            </div>
          )}

          {/* TAB 2: Browser Upload (Drag & Drop) */}
          {activeTab === 'browser_upload' && (
            <div className="space-y-5">
              <p className="text-neutral-600 leading-relaxed text-xs">
                黒い画面やコマンド入力は不要です。ブラウザだけで完結します。
              </p>

              <div className="space-y-3">
                <div className="p-4 bg-[#f8fafc] border border-neutral-200 rounded-2xl flex items-start gap-3">
                  <span className="w-6 h-6 rounded-full bg-[#081a2e] text-white font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">1</span>
                  <div className="space-y-1.5 flex-1">
                    <h5 className="font-bold text-[#081a2e]">ZIPをダウンロードして解凍する</h5>
                    <p className="text-neutral-600 text-xs">
                      ダウンロードした <code>{repoName}.zip</code> をダブルクリックして解凍してください。
                    </p>
                    <button
                      onClick={handleDownloadZip}
                      disabled={isGenerating}
                      className="px-4 py-2 bg-[#f59e0b] hover:bg-[#d97706] text-[#081a2e] font-bold text-xs rounded-xl shadow-xs transition-colors flex items-center gap-1.5"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>ZIPをダウンロード</span>
                    </button>
                  </div>
                </div>

                <div className="p-4 bg-[#f8fafc] border border-neutral-200 rounded-2xl flex items-start gap-3">
                  <span className="w-6 h-6 rounded-full bg-[#081a2e] text-white font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">2</span>
                  <div className="space-y-1.5 flex-1">
                    <h5 className="font-bold text-[#081a2e]">GitHubで新しいリポジトリを作成</h5>
                    <p className="text-neutral-600 text-xs">
                      Repository nameに「<code>{repoName}</code>」と入力して「Create repository」を押します。
                    </p>
                    <a
                      href="https://github.com/new"
                      target="_blank"
                      rel="noreferrer"
                      className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-white border border-neutral-300 text-neutral-800 font-semibold text-xs rounded-xl shadow-xs"
                    >
                      <span>github.com/new を開く</span>
                      <ExternalLink className="w-3.5 h-3.5" />
                    </a>
                  </div>
                </div>

                <div className="p-4 bg-[#f8fafc] border border-neutral-200 rounded-2xl flex items-start gap-3">
                  <span className="w-6 h-6 rounded-full bg-[#081a2e] text-white font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">3</span>
                  <div className="space-y-1 flex-1">
                    <h5 className="font-bold text-[#081a2e]">ドラッグ＆ドロップして「Commit changes」</h5>
                    <p className="text-neutral-600 text-xs leading-relaxed">
                      作成後の画面の「uploading an existing file」リンクをクリックし、解凍したフォルダの中身をすべて画面にドラッグ＆ドロップして保存するだけです！
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: Git Terminal */}
          {activeTab === 'git_terminal' && (
            <div className="space-y-4">
              <div className="flex items-center gap-3 bg-[#f8fafc] p-3 rounded-2xl border border-neutral-200">
                <label className="text-neutral-600 font-semibold">GitHubユーザー名:</label>
                <input
                  type="text"
                  value={githubUsername}
                  onChange={(e) => setGithubUsername(e.target.value.trim())}
                  placeholder="例: fleiss-gk"
                  className="bg-white border border-neutral-300 rounded-xl px-3 py-1.5 text-neutral-800 font-mono text-xs w-48"
                />
              </div>

              <div className="relative bg-[#081a2e] border border-neutral-800 rounded-2xl p-5 font-mono text-[11px] text-neutral-200 leading-relaxed overflow-x-auto">
                <button
                  onClick={handleCopyCommands}
                  className="absolute top-3.5 right-3.5 flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#132c4a] hover:bg-[#1a385c] text-neutral-100 text-xs transition-colors"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'コピー完了' : 'コマンドを一括コピー'}
                </button>
                <pre>{gitCommands}</pre>
              </div>
            </div>
          )}

          {/* TAB 4: JSON Backup */}
          {activeTab === 'json_backup' && (
            <div className="space-y-5">
              <div className="bg-[#f8fafc] border border-neutral-200 p-5 rounded-2xl space-y-3">
                <h4 className="font-bold text-[#081a2e] text-sm">現在の全データをJSONファイルとして保存</h4>
                <button
                  onClick={() => {
                    const dataStr = JSON.stringify({ drills, players }, null, 2);
                    const blob = new Blob([dataStr], { type: 'application/json' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `fleiss_gk_studio_backup.json`;
                    a.click();
                    URL.revokeObjectURL(url);
                  }}
                  className="flex items-center gap-1.5 px-4 py-2 bg-[#081a2e] hover:bg-[#132c4a] text-white font-bold text-xs rounded-xl shadow-xs transition-colors"
                >
                  <Download className="w-4 h-4" />
                  <span>JSONバックアップをダウンロード</span>
                </button>
              </div>

              <div className="bg-[#f8fafc] border border-neutral-200 p-5 rounded-2xl space-y-3">
                <h4 className="font-bold text-[#081a2e] text-sm">バックアップからデータを復元</h4>
                <label className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs rounded-xl cursor-pointer shadow-xs transition-colors">
                  <Upload className="w-4 h-4" />
                  <span>JSONファイルを選択して復元</span>
                  <input
                    type="file"
                    accept=".json"
                    onChange={handleFileUpload}
                    className="hidden"
                  />
                </label>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
